vm_name = "windows-vm-ext-int-ip"
zone = "us-west2-a"
region = "us-west2" 
subnet = "external-test"
network = "external"
machine_type = "f1-micro" 
image = "windows-cloud/windows-2012-r2"
disk_size = "65"
